//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DurakGame.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DurakGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-----------------------------------------------------------------------------------------------------------------------------------
        ///    FILE:           frmAbout.html                                                                                                
        ///     LANGUAGE:      HYPER TEXT MARKUP LANGUAGE FILE                                                                              
        ///    AUTHOR:         GROUP IV                                                                                        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AboutHTML {
            get {
                return ResourceManager.GetString("AboutHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_back_1 {
            get {
                object obj = ResourceManager.GetObject("card_back_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_back_2 {
            get {
                object obj = ResourceManager.GetObject("card_back_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_back_3 {
            get {
                object obj = ResourceManager.GetObject("card_back_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_back_4 {
            get {
                object obj = ResourceManager.GetObject("card_back_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap club {
            get {
                object obj = ResourceManager.GetObject("club", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap diamond {
            get {
                object obj = ResourceManager.GetObject("diamond", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--------------------------------------------------------------------------------------------
        ///    FILE:           footer.html  
        ///                    HYPER TEXT MARKUP LANGUAGE FILE
        ///    AUTHOR:         GROUP IV
        ///                    SECTION I
        ///                    GREGORY HAMMOND, JOEL ROTH, JESSE MCDONALD
        ///    SUBJECT:        DURHAM COLLEGE
        ///                    COMPUTER PROGRAMMER ANALYST
        ///                    DNET   4200
        ///                    DURAK PROJECT
        ///    DATE:           2015
        ///
        ///    DESCRIPTION:    An [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string footer {
            get {
                return ResourceManager.GetString("footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon form_icon {
            get {
                object obj = ResourceManager.GetObject("form_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--------------------------------------------------------------------------------
        ///    FILE:           frmAbout.html
        ///     LANGUAGE:      HYPER TEXT MARKUP LANGUAGE FILE
        ///    AUTHOR:         GROUP IV
        ///                    SECTION I
        ///                    GREGORY HAMMOND, JOEL ROTH, JESSE MCDONALD
        ///    SUBJECT:        DURHAM COLLEGE
        ///                    COMPUTER PROGRAMMER ANALYST
        ///                    DNET   4200
        ///                    DURAK PROJECT
        ///    DATE:           2015
        ///
        ///    DESCRIPTION:    An HTML help f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GameplayHTML {
            get {
                return ResourceManager.GetString("GameplayHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--------------------------------------------------------------------------------------------
        ///    FILE:           header.html  
        ///                    HYPER TEXT MARKUP LANGUAGE FILE
        ///    AUTHOR:         GROUP IV
        ///                    SECTION I
        ///                    GREGORY HAMMOND, JOEL ROTH, JESSE MCDONALD
        ///    SUBJECT:        DURHAM COLLEGE
        ///                    COMPUTER PROGRAMMER ANALYST
        ///                    DNET   4200
        ///                    DURAK PROJECT
        ///    DATE:           2015
        ///
        ///    DESCRIPTION:    An [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string header {
            get {
                return ResourceManager.GetString("header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap heart {
            get {
                object obj = ResourceManager.GetObject("heart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /************
        ///    *   Aa  *
        ///    ************/
        ///a{  color:  #38A2F9; }
        ///
        ///
        ///
        ///
        ////************
        ///    *   Bb  *
        ///    ************/
        ///body
        ///{
        ///    background-color:   #000;
        ///    color:              #FFF; 
        ///    font-family:        &apos;Segoe UI&apos;;
        ///}
        ///
        ///
        ///
        ///
        ////************
        ///    *   Hh  *
        ///    ************/
        ///h1 
        ///{ 
        ///    font-size:      22pt; 
        ///    font-weight:    normal; 
        ///}
        ///
        ///h2 
        ///{ 
        ///    font-size:      18pt; 
        ///    font-weight:    normal; 
        ///}
        ///            
        ///h3 
        ///{ 
        ///    font-size:      14pt; 
        ///    font-weight:     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MainCSS {
            get {
                return ResourceManager.GetString("MainCSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-------------------------------------------------------------------------------
        ///    FILE:           setup.html                                                  
        ///    LANGUAGE:       HYPER TEXT MARKUP LANGUAGE FILE                             
        ///    AUTHOR:         GROUP IV                                                    
        ///                    SECTION I                                                   
        ///                    GREGORY HAMMOND, JOEL ROTH, JESSE MCDONALD                  
        ///    SUBJECT:        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ObjectivesHTML {
            get {
                return ResourceManager.GetString("ObjectivesHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-------------------------------------------------------------------------------
        ///    FILE:           setup.html                                                  -
        ///                    HYPER TEXT MARKUP LANGUAGE FILE                             -
        ///    AUTHOR:         GROUP IV                                                    -
        ///                    SECTION I                                                   -
        ///                    JESSE MCDONALD                                              -
        ///    SUBJECT:   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SetupHTML {
            get {
                return ResourceManager.GetString("SetupHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spade {
            get {
                object obj = ResourceManager.GetObject("spade", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap transparent_back {
            get {
                object obj = ResourceManager.GetObject("transparent_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-----------------------------------------------------------------------------------------------------------------------------------
        ///    FILE:           frmTutorial.html                                                                                             
        ///    LANGUAGE:       HYPER TEXT MARKUP LANGUAGE FILE                                                                              
        ///    AUTHOR:         GROUP IV                                                                                        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TutorialHTML {
            get {
                return ResourceManager.GetString("TutorialHTML", resourceCulture);
            }
        }
    }
}
